export const logo = [
  {
    name: 'Docker',
    value: 'docker',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/docker.png',
    type: 'framework',
  },
  {
    name: 'ExpressJS',
    value: 'expressjs',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/expressjs.png',
    type: 'framework',
  },
  {
    name: 'Firebase',
    value: 'firebase',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/firebase.png',
    type: 'database',
  },
  {
    name: 'GraphQL',
    value: 'graphql',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/graphql.png',
    type: 'framework',
  },
  {
    name: 'Javascript',
    value: 'javascript',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/javascript.png',
    type: 'language',
  },
  {
    name: 'MongoDB',
    value: 'mongodb',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/mongodb.png',
    type: 'database',
  },
  {
    name: 'MySQL',
    value: 'mysql',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/mysql.png',
    type: 'database',
  },
  {
    name: 'NestJS',
    value: 'nestjs',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/nestjs.png',
    type: 'framework',
  },
  {
    name: 'NextJS',
    value: 'nextjs',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/nextjs.png',
    type: 'framework',
  },
  {
    name: 'NodeJS',
    value: 'nodejs',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/nodejs.png',
    type: 'language',
  },
  {
    name: 'PHP',
    value: 'php',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/php.png',
    type: 'language',
  },
  {
    name: 'PostgreSQL',
    value: 'postgresql',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/postgresql.png',
    type: 'database',
  },
  {
    name: 'RabbitMQ',
    value: 'rabbitmq',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/rabbitmq.png',
    type: 'database',
  },
  {
    name: 'ReactJS',
    value: 'reactjs',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/reactjs.png',
    type: 'framework',
  },
  {
    name: 'Redis',
    value: 'redis',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/redis.png',
    type: 'database',
  },
  {
    name: 'Typescript',
    value: 'typescript',
    url: process.env.NODE_ENV === "production" ? "/my-portfolio" : "" + '/assets/logo/typescript.png',
    type: 'language',
  },
]
